### ISSUE TITLE
Math questions failing on text input

### ISSUE THREAD

**Issue by syntaxseed** [theodorejb/Responsive-Captcha#1]
Entering a textual answer for a math question is failing. This is because you convert the $realAns to a string if it's an int, but you don't convert it if it's an int (stored that way by default) and the $answer is string. Changed this function to fix:

``` PHP
public function checkAnswer($submittedResponse)
    {
        // convert the answer to lower case and trim any whitespace
        $answer  = strtolower(trim($submittedResponse));
        $realAns = $this->getAnswer();

        // both numeric and textual answers are acceptable
        if( is_int($answer) ){
            $answer = $this->getWordFromNumber($answer);
        }
        if( is_int($realAns) ){
            $realAns = $this->getWordFromNumber($realAns);
        }

        return (strcmp($answer, $realAns)==0);
    }
```

**Comment by syntaxseed** [comment]
Correction (due to form input never being int type):

``` PHP
public function checkAnswer($submittedResponse)
    {
        // convert the answer to lower case and trim any whitespace
        $answer  = strtolower(trim($submittedResponse));
        $realAns = $this->getAnswer();

        // both numeric and textual answers are acceptable
        if( is_numeric($answer) ){
            $answer = $this->getWordFromNumber(intval($answer));
        }
        if( is_numeric($realAns) ){
            $realAns = $this->getWordFromNumber(intval($realAns));
        }

        return (strcmp($answer, $realAns)==0);
    }
```

**Comment by syntaxseed** [comment]
Also, the exceptions throw in the getWordFromNumber($number) function should be replaced by just returning the number. Otherwise users can reliably cause exceptions by entering numbers larger than 100. (Many bots just enter 12345 into form fields they don't recognize).

This way the captcha test just gives false rather than throwing exceptions all over the place.

**Comment by theodorejb** [comment]
Thanks for reporting this! The issue occurred because an answer was only compared to the textual version of a number if it was an integer, but of course a textual number is never an int.

Note that there is no need to pass user data to `getWordFromNumber` (with a potential for exceptions). Only the real answer needs to be passed.
